org: ziggyganymede
app: ping-climb-tulsa
service: ping-climb-tulsa

frameworkVersion: '3'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getClimbers:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 hour)

custom:
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: true # enable autopacking of Node modules
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore